//
// AUTO-GENERATED by craft-schema -- do not edit by hand.
// Regenerate with: cargo run -p craft-schema --bin gen-sdk
//
// AUTO-GENERATED by craft-schema — do not edit.
// Source of truth: ActionParams enum in crates/craft-schema/src/lib.rs
// Regenerate by running `cargo run -p craft-schema --bin gen-sdk`.

export type SceneKind = "scene";

export type Target =
  | { kind: "self" }
  | { kind: "node"; id: string }
  | { kind: "parent" }
  | { kind: "children"; filter?: string };

export type Expression =
  | { ref: string }
  | { eq: Expression[] }
  | { neq: Expression[] }
  | { lt: Expression[] }
  | { gt: Expression[] }
  | { add: Expression[] }
  | { sub: Expression[] }
  | string | number | boolean | null;

export type LogLevel = "debug" | "info" | "warning" | "error";

export type SetStateAction = {
  kind: "set_state";
  target: Target;
  key: string;
  value: unknown;
};

export type EmitAction = {
  kind: "emit";
  signal: string;
  args?: Record<string, unknown>;
};

export type DestroyAction = {
  kind: "destroy";
  target: Target;
};

export type SpawnAction = {
  kind: "spawn";
  type: string;
  parent: Target;
  components?: Record<string, unknown>;
};

export type IfAction = {
  kind: "if";
  cond: Expression;
  then: Action[];
  else?: Action[];
};

export type MoveAction = {
  kind: "move";
  target: Target;
  key: string;
  by: unknown;
};

export type AnimateAction = {
  kind: "animate";
  target: Target;
  key: string;
  to: unknown;
  duration: number;
};

export type LogAction = {
  kind: "log";
  level: LogLevel;
  message: string;
  fields?: Record<string, unknown>;
};

export type CallSystemAction = {
  kind: "call_system";
  system: string;
  args?: Record<string, unknown>;
  result_in?: { key: string; on: Target };
};

export type Action =
  | SetStateAction
  | EmitAction
  | DestroyAction
  | SpawnAction
  | IfAction
  | MoveAction
  | AnimateAction
  | LogAction
  | CallSystemAction;

export const ACTION_VERBS = [
  "set_state",
  "emit",
  "destroy",
  "spawn",
  "if",
  "move",
  "animate",
  "log",
  "call_system",
] as const;

export type ActionVerb = typeof ACTION_VERBS[number];
