use craft_bridge::Bridge;
use craft_kernel::Scene;
use craft_kernel::craft_node;
use craft_kernel::serde_json::json;
use craft_schema::{
    ACTION_VERBS, action_verb_descriptions, get_action_schema, get_full_schema, is_valid_verb,
    typescript_sdk_types,
};

craft_node!(M7Player, {
    components: {
        health: Int = 100,
        position: Vec2 = [0.0, 0.0],
    },
});

fn loaded_bridge() -> Bridge {
    let mut bridge = Bridge::new();
    let scene_value: serde_json::Value = serde_json::from_str(
        r#"{
        "kind": "scene",
        "name": "m7",
        "nodes": [
            {
                "id": "p1",
                "type": "M7Player",
                "components": { "health": 100, "position": [0.0, 0.0] }
            }
        ]
    }"#,
    )
    .unwrap();
    let registry = bridge.engine().nodes.clone();
    let scene = Scene::from_value(scene_value, "scene.json", &registry).expect("scene from value");
    bridge.engine_mut().load_scene(scene);
    bridge
}

fn make_request(method: &str, params: serde_json::Value, id: u32) -> String {
    serde_json::json!({
        "jsonrpc": "2.0",
        "method": method,
        "params": params,
        "id": id,
    })
    .to_string()
}

#[test]
fn schema_has_nine_action_verbs() {
    assert_eq!(ACTION_VERBS.len(), 9);
}

#[test]
fn all_verbs_are_valid() {
    for verb in ACTION_VERBS {
        assert!(is_valid_verb(verb), "{verb} should be valid");
    }
    assert!(!is_valid_verb("bogus"));
}

#[test]
fn every_verb_has_a_description() {
    let descs = action_verb_descriptions();
    for verb in ACTION_VERBS {
        assert!(descs.contains_key(verb), "missing description for {verb}");
        assert!(!descs[verb].is_empty(), "empty description for {verb}");
    }
}

#[test]
fn get_action_schema_returns_schema_for_every_verb() {
    for verb in ACTION_VERBS {
        let schema = get_action_schema(verb);
        assert!(schema.is_some(), "no schema for {verb}");
    }
    assert!(get_action_schema("nope").is_none());
}

#[test]
fn set_state_schema_documents_required_fields() {
    let schema = get_action_schema("set_state").expect("schema");
    let v = serde_json::to_value(schema).expect("serialize");
    let required = v["required"]
        .as_array()
        .expect("required array")
        .iter()
        .filter_map(|r| r.as_str())
        .collect::<Vec<_>>();
    assert!(required.contains(&"target"));
    assert!(required.contains(&"key"));
    assert!(required.contains(&"value"));
}

#[test]
fn emit_schema_documents_signal_field() {
    let schema = get_action_schema("emit").expect("schema");
    let v = serde_json::to_value(schema).expect("serialize");
    let required = v["required"]
        .as_array()
        .expect("required array")
        .iter()
        .filter_map(|r| r.as_str())
        .collect::<Vec<_>>();
    assert!(required.contains(&"signal"));
}

#[test]
fn animate_schema_documents_duration_as_u32() {
    let schema = get_action_schema("animate").expect("schema");
    let v = serde_json::to_value(schema).expect("serialize");
    let properties = v["properties"].as_object().expect("properties");
    assert!(properties.contains_key("duration"));
}

#[test]
fn full_schema_contains_version_and_verbs() {
    let full = get_full_schema();
    assert_eq!(full["version"], "1.0");
    let verbs = full["verbs"].as_array().expect("verbs array");
    assert_eq!(verbs.len(), 9);
    let descs = full["verb_descriptions"]
        .as_object()
        .expect("verb_descriptions");
    for verb in ACTION_VERBS {
        assert!(descs.contains_key(*verb));
    }
}

#[test]
fn typescript_types_contains_all_action_aliases() {
    let ts = typescript_sdk_types();
    for alias in [
        "SetStateAction",
        "EmitAction",
        "DestroyAction",
        "SpawnAction",
        "IfAction",
        "MoveAction",
        "AnimateAction",
        "LogAction",
        "CallSystemAction",
    ] {
        assert!(ts.contains(alias), "TS missing {alias}");
    }
}

#[test]
fn typescript_types_contains_verb_array() {
    let ts = typescript_sdk_types();
    for verb in ACTION_VERBS {
        assert!(
            ts.contains(&format!("\"{verb}\"")),
            "TS missing verb {verb}"
        );
    }
    assert!(ts.contains("ACTION_VERBS"));
    assert!(ts.contains("ActionVerb"));
}

#[test]
fn typescript_types_starts_with_auto_generated_marker() {
    let ts = typescript_sdk_types();
    assert!(ts.starts_with("// AUTO-GENERATED by craft-schema"));
}

#[test]
fn bridge_get_action_schema_returns_valid_json_schema() {
    let mut bridge = loaded_bridge();
    let req = make_request("engine.getActionSchema", json!({"verb": "set_state"}), 1);
    let resp: serde_json::Value = serde_json::from_str(&bridge.dispatch_str(&req)).unwrap();
    assert!(resp["error"].is_null() || resp.get("error").is_none());
    let result = resp["result"].as_object().expect("result");
    assert_eq!(result["verb"], "set_state");
    let schema = result["schema"].as_object().expect("schema");
    assert!(schema.contains_key("properties"));
    let required = schema["required"]
        .as_array()
        .expect("required")
        .iter()
        .filter_map(|r| r.as_str())
        .collect::<Vec<_>>();
    assert!(required.contains(&"target"));
    assert!(required.contains(&"key"));
    assert!(required.contains(&"value"));
}

#[test]
fn bridge_get_action_schema_for_unknown_verb_returns_error() {
    let mut bridge = loaded_bridge();
    let req = make_request("engine.getActionSchema", json!({"verb": "bogus"}), 2);
    let resp: serde_json::Value = serde_json::from_str(&bridge.dispatch_str(&req)).unwrap();
    assert_eq!(resp["error"]["code"], -32602);
    assert!(resp["error"]["message"].as_str().unwrap().contains("bogus"));
}

#[test]
fn bridge_get_action_schema_for_all_nine_verbs() {
    let mut bridge = loaded_bridge();
    for (i, verb) in ACTION_VERBS.iter().enumerate() {
        let req = make_request(
            "engine.getActionSchema",
            json!({"verb": verb}),
            (i + 100) as u32,
        );
        let resp: serde_json::Value = serde_json::from_str(&bridge.dispatch_str(&req)).unwrap();
        assert!(resp["error"].is_null() || resp.get("error").is_none());
        assert_eq!(resp["result"]["verb"], *verb);
        assert!(!resp["result"]["description"].as_str().unwrap().is_empty());
    }
}

#[test]
fn bridge_get_schema_includes_schema_source() {
    let mut bridge = loaded_bridge();
    let req = make_request("engine.getSchema", json!({}), 1);
    let resp: serde_json::Value = serde_json::from_str(&bridge.dispatch_str(&req)).unwrap();
    assert_eq!(resp["result"]["schema_source"], "craft-schema");
}

#[test]
fn ts_sdk_includes_target_and_expression_types() {
    let ts = typescript_sdk_types();
    assert!(ts.contains("export type Target"));
    assert!(ts.contains("export type Expression"));
    assert!(ts.contains("export type LogLevel"));
    assert!(ts.contains("\"self\""));
    assert!(ts.contains("\"node\""));
    assert!(ts.contains("\"parent\""));
    assert!(ts.contains("\"children\""));
}

#[test]
fn ts_sdk_action_union_includes_all_verbs() {
    let ts = typescript_sdk_types();
    let action_section = ts
        .split("export type Action =")
        .nth(1)
        .expect("Action type");
    for verb in ACTION_VERBS {
        assert!(action_section.contains(verb), "Action union missing {verb}");
    }
}
